'use strict';
// Explicit ES module graph -> single Cloudflare module Worker.
const fs = require('node:fs');
const path = require('node:path');
const { buildSync } = require('esbuild');

function buildBundle() {
  return buildSync({
    absWorkingDir: __dirname,
    entryPoints: ['src/main.js'],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    charset: 'utf8',
    external: ['cloudflare:sockets', 'node:async_hooks'],
    legalComments: 'none',
    banner: { js: '// Generated by build.js from ES Modules. Do not edit.' },
  }).outputFiles[0].text;
}

function main() {
  let out, check = false, force = false;
  const args = process.argv.slice(2);
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--out' && args[i + 1] && !args[i + 1].startsWith('--')) out = args[++i];
    else if (args[i] === '--check') check = true;
    else if (args[i] === '--force') force = true;
    else throw new Error(`未知参数或缺少参数值: ${args[i]}`);
  }
  const bundle = buildBundle();
  if (out) {
    const dest = path.resolve(__dirname, out);
    if (fs.existsSync(dest) && !force) throw new Error('目标已存在；使用 --force 覆盖');
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, bundle);
    console.log(`[build] ES Modules -> ${out} (${Buffer.byteLength(bundle)} 字节)`);
  } else if (!check) process.stdout.write(bundle);
  else console.log('[build] ES Modules 解析、链接、打包通过；未写入文件');
}
if (require.main === module) {
  try { main(); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
module.exports = { buildBundle };
